# Generated by Django 3.0.6 on 2020-05-05 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prescriptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_url', models.URLField(max_length=256)),
                ('od_power_sph', models.CharField(blank=True, max_length=60, null=True)),
                ('od_bc', models.CharField(blank=True, max_length=56, null=True)),
                ('od_axis', models.CharField(blank=True, max_length=56, null=True)),
                ('os_power_sph', models.CharField(blank=True, max_length=56, null=True)),
                ('os_bc', models.CharField(blank=True, max_length=56, null=True)),
                ('od_dia', models.CharField(blank=True, max_length=56, null=True)),
                ('od_cyl', models.CharField(blank=True, max_length=56, null=True)),
                ('os_axis', models.CharField(blank=True, max_length=56, null=True)),
            ],
        ),
    ]
